randdamage: false
randchat: false
randsheep: false
donotsneak: false
auto: false
the24: false
morediamond: false
morecoal: false
moregold: false
moreemerald: false
morelapis: false
morecopper: false
moreiron: false
moreredstone: false
superSponges: []
spongeR: 16