name: BluestarGame
version: '${project.version}'
main: me.lanzhi.bluestargame.BluestarGame
api-version: 1.18
commands:
  bluestargame:
    aliases:
      - bsgame
    permission: bluestargame.use
  bluestargamelist:
    aliases:
      - bsgamelist
      - bsglist
permissions:
  bluestargame.*:
    children:
      bluestargame.use:
        default: op
      bluestargame.lanzhi:
        default: false
depend:
  - BluestarAPI
  - NBTAPI