name: BluestarGame
version: '${project.version}'
main: me.lanzhi.bluestargame.BluestarGame
api-version: 1.18
commands:
  bluestargame:
    aliases:
      - bsgame
    permission: bluestargame.use
    description: 玩法控制
  bluestargamelist:
    aliases:
      - bsgamelist
      - bsglist
    description: 查看当前启用的玩法
permissions:
  bluestargame.*:
    description: 所有权限
    children:
      bluestargame.use:
        description: 允许使用/bluestargame,默认op
        default: op
      bluestargame.lanzhi:
        description: 腐竹专属,用于腐竹自己调试插件,默认false
        default: false
depend:
  - BluestarAPI
  - NBTAPI