name: BluestarGame
version: '${project.version}'
main: me.lanzhi.bluestargame.BluestarGamePlugin
api-version: 1.18
website: https://github.com/lanzhi6/BluestarGame
author: lanzhi
commands:
  test:
    permission: bluestargame.lanzhi
  bluestargame:
    aliases:
      - bsgame
    permission: bluestargame.use
    description: 玩法控制
    usage: /bluestargame 项目 <其他>
  bluestargamelist:
    aliases:
      - bsgamelist
      - bsglist
    description: 查看当前启用的玩法
    usage: /bluestargamelist
  muted:
    description: 禁言
    permission: bluestargame.use
    permission-message: bluestargame.use
  chat:
    description: 让别的玩家发送消息
    permission: bluestargame.use
    usage: /chat 玩家 内容
  bluestaritem:
    aliases:
      - bsitem
      - bsgitem
      - bsgameitem
      - bluestargameitem
    permission: bluestargame.use
  elevator:
    permission: bluestargame.elevator
  xiaomobank:
    aliases:
      - xmbank
  shape:
    permission: bluestargame.use
  cmdbag:
    aliases:
      - commandbag
  setnick:
    aliases:
      - nick
permissions:
  bluestargame.*:
    description: 所有权限
    children:
      bluestargame.elevator:
        description: 允许使用电梯相关功能
        default: op
      bluestargame.use:
        description: 允许使用/bluestargame,默认op
        default: op
      bluestargame.lanzhi:
        description: 腐竹专属,用于腐竹自己调试插件,默认false
        default: false
      bluestargame.color:
        description: 使用颜色代码
        default: op
depend:
  - BluestarAPI
  - NBTAPI
  - PlaceholderAPI
  - BluestarQQ
  - MiraiMC
  - Vault
  - BluestarGameAPI