name: BluestarGame
version: '${project.version}'
main: me.lanzhi.bluestargame.BluestarGame
api-version: 1.18
website: https://github.com/lanzhi6/BluestarGame
author: lanzhi
commands:
  bluestargame:
    aliases:
      - bsgame
    permission: bluestargame.use
    description: 玩法控制
  bluestargamelist:
    aliases:
      - bsgamelist
      - bsglist
    description: 查看当前启用的玩法
  muted:
    description: 禁言
    permission: bluestargame.use
    permission-message: bluestargame.use
  chat:
    description: 让别的玩家发送消息
    permission: bluestargame.use
  bluestaritem:
    aliases:
      - bsitem
      - bsgitem
      - bsgameitem
      - bluestargameitem
    permission: bluestargame.use
  elevator:
    permission: bluestargame.elevator
permissions:
  bluestargame.*:
    description: 所有权限
    children:
      bluestargame.elevator:
        description: 允许使用电梯相关功能
        default: op
      bluestargame.use:
        description: 允许使用/bluestargame,默认op
        default: op
      bluestargame.lanzhi:
        description: 腐竹专属,用于腐竹自己调试插件,默认false
        default: false
depend:
  - BluestarAPI
  - NBTAPI
  - PlaceholderAPI